"""add missing order columns

Revision ID: 0007
Revises: 0006
Create Date: 2025-09-17 08:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('order_data', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('customer_count', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('assigned_seats', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('modifiers', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'modifiers')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'assigned_seats')
    op.drop_column('orders', 'customer_count')
    op.drop_column('orders', 'table_id')
    op.drop_column('orders', 'order_data')
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###