"""add order_id to kitchen_orders table

Revision ID: 0009
Revises: 0008
Create Date: 2025-09-17 08:50:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitchen_orders', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kitchen_orders', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kitchen_orders', type_='foreignkey')
    op.drop_column('kitchen_orders', 'order_id')
    # ### end Alembic commands ###