version: "3.9"

services:
  web:
    command: uvicorn main:app --host 0.0.0.0 --port 8088 --reload
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@db:5432/mydb}
      SECRET_KEY: ${SECRET_KEY:-BEGmxdg7h0z-TUYdtsJKfXxu-_xVvj3CgFdJy9aK24c}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      ENVIRONMENT: development
    volumes:
      - ./app:/app