version: "3.9"

services:
  db-backup:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    command: >
      bash -c "
        apt-get update && apt-get install -y cron &&
        echo '0 2 * * * pg_dump -U postgres mydb > /backups/postgres_backup_\$$(date +\%Y\%m\%d_\%H\%M\%S).sql' | crontab - &&
        cron -f
      "
    depends_on:
      - db

volumes:
  postgres_data:
    external: true